/** Github
 * References
 *   - [create repository](https://octokit.github.io/rest.js/v19#repos-create-for-authenticated-user)
 */
import { Octokit } from '@octokit/rest';
import type { GithubAccount, RepoOptions, IssueListOptions, IssueCreateOptions, IssueUpdateOptions, ProjectListOptions, ProjectCreateOptions, ProjectColumnOptions, ProjectCardOptions, WorkflowDispatchOptions, WorkflowListOptions, WorkflowRunsOptions } from './types.js';
/**
 * Github 계정 정보 조회
 * @param userName - Github 사용자명
 * @returns Github 계정 정보
 *
 * @example
 * ```ts
 * const account = findGithubAccount('username');
 * ```
 */
declare const findGithubAccount: (userName: string, src?: string) => Promise<GithubAccount | undefined>;
/**
 * 모든 저장소 목록 조회
 */
declare const findAllRepos: (octokit: Octokit) => Promise<{
    id: number;
    node_id: string;
    name: string;
    full_name: string;
    license: {
        key: string;
        name: string;
        url: string | null;
        spdx_id: string | null;
        node_id: string;
        html_url?: string | undefined;
    } | null;
    forks: number;
    permissions?: {
        admin: boolean;
        pull: boolean;
        triage?: boolean | undefined;
        push: boolean;
        maintain?: boolean | undefined;
    } | undefined;
    owner: {
        name?: string | null | undefined;
        email?: string | null | undefined;
        login: string;
        id: number;
        node_id: string;
        avatar_url: string;
        gravatar_id: string | null;
        url: string;
        html_url: string;
        followers_url: string;
        following_url: string;
        gists_url: string;
        starred_url: string;
        subscriptions_url: string;
        organizations_url: string;
        repos_url: string;
        events_url: string;
        received_events_url: string;
        type: string;
        site_admin: boolean;
        starred_at?: string | undefined;
        user_view_type?: string | undefined;
    };
    private: boolean;
    html_url: string;
    description: string | null;
    fork: boolean;
    url: string;
    archive_url: string;
    assignees_url: string;
    blobs_url: string;
    branches_url: string;
    collaborators_url: string;
    comments_url: string;
    commits_url: string;
    compare_url: string;
    contents_url: string;
    contributors_url: string;
    deployments_url: string;
    downloads_url: string;
    events_url: string;
    forks_url: string;
    git_commits_url: string;
    git_refs_url: string;
    git_tags_url: string;
    git_url: string;
    issue_comment_url: string;
    issue_events_url: string;
    issues_url: string;
    keys_url: string;
    labels_url: string;
    languages_url: string;
    merges_url: string;
    milestones_url: string;
    notifications_url: string;
    pulls_url: string;
    releases_url: string;
    ssh_url: string;
    stargazers_url: string;
    statuses_url: string;
    subscribers_url: string;
    subscription_url: string;
    tags_url: string;
    teams_url: string;
    trees_url: string;
    clone_url: string;
    mirror_url: string | null;
    hooks_url: string;
    svn_url: string;
    homepage: string | null;
    language: string | null;
    forks_count: number;
    stargazers_count: number;
    watchers_count: number;
    size: number;
    default_branch: string;
    open_issues_count: number;
    is_template?: boolean | undefined;
    topics?: string[] | undefined;
    has_issues: boolean;
    has_projects: boolean;
    has_wiki: boolean;
    has_pages: boolean;
    has_downloads: boolean;
    has_discussions?: boolean | undefined;
    archived: boolean;
    disabled: boolean;
    visibility?: string | undefined;
    pushed_at: string | null;
    created_at: string | null;
    updated_at: string | null;
    allow_rebase_merge?: boolean | undefined;
    temp_clone_token?: string | undefined;
    allow_squash_merge?: boolean | undefined;
    allow_auto_merge?: boolean | undefined;
    delete_branch_on_merge?: boolean | undefined;
    allow_update_branch?: boolean | undefined;
    use_squash_pr_title_as_default?: boolean | undefined;
    squash_merge_commit_title?: "PR_TITLE" | "COMMIT_OR_PR_TITLE" | undefined;
    squash_merge_commit_message?: "PR_BODY" | "COMMIT_MESSAGES" | "BLANK" | undefined;
    merge_commit_title?: "PR_TITLE" | "MERGE_MESSAGE" | undefined;
    merge_commit_message?: "PR_TITLE" | "PR_BODY" | "BLANK" | undefined;
    allow_merge_commit?: boolean | undefined;
    allow_forking?: boolean | undefined;
    web_commit_signoff_required?: boolean | undefined;
    open_issues: number;
    watchers: number;
    master_branch?: string | undefined;
    starred_at?: string | undefined;
    anonymous_access_enabled?: boolean | undefined;
}[]>;
/**
 * 새 저장소 생성
 */
declare const createRemoteRepo: (octokit: Octokit, options: RepoOptions) => Promise<import("@octokit/types").OctokitResponse<{
    id: number;
    node_id: string;
    name: string;
    full_name: string;
    owner: {
        name?: string | null | undefined;
        email?: string | null | undefined;
        login: string;
        id: number;
        node_id: string;
        avatar_url: string;
        gravatar_id: string | null;
        url: string;
        html_url: string;
        followers_url: string;
        following_url: string;
        gists_url: string;
        starred_url: string;
        subscriptions_url: string;
        organizations_url: string;
        repos_url: string;
        events_url: string;
        received_events_url: string;
        type: string;
        site_admin: boolean;
        starred_at?: string | undefined;
        user_view_type?: string | undefined;
    };
    private: boolean;
    html_url: string;
    description: string | null;
    fork: boolean;
    url: string;
    archive_url: string;
    assignees_url: string;
    blobs_url: string;
    branches_url: string;
    collaborators_url: string;
    comments_url: string;
    commits_url: string;
    compare_url: string;
    contents_url: string;
    contributors_url: string;
    deployments_url: string;
    downloads_url: string;
    events_url: string;
    forks_url: string;
    git_commits_url: string;
    git_refs_url: string;
    git_tags_url: string;
    git_url: string;
    issue_comment_url: string;
    issue_events_url: string;
    issues_url: string;
    keys_url: string;
    labels_url: string;
    languages_url: string;
    merges_url: string;
    milestones_url: string;
    notifications_url: string;
    pulls_url: string;
    releases_url: string;
    ssh_url: string;
    stargazers_url: string;
    statuses_url: string;
    subscribers_url: string;
    subscription_url: string;
    tags_url: string;
    teams_url: string;
    trees_url: string;
    clone_url: string;
    mirror_url: string | null;
    hooks_url: string;
    svn_url: string;
    homepage: string | null;
    language: string | null;
    forks_count: number;
    stargazers_count: number;
    watchers_count: number;
    size: number;
    default_branch: string;
    open_issues_count: number;
    is_template?: boolean | undefined;
    topics?: string[] | undefined;
    has_issues: boolean;
    has_projects: boolean;
    has_wiki: boolean;
    has_pages: boolean;
    has_downloads?: boolean | undefined;
    has_discussions: boolean;
    archived: boolean;
    disabled: boolean;
    visibility?: string | undefined;
    pushed_at: string;
    created_at: string;
    updated_at: string;
    permissions?: {
        admin: boolean;
        maintain?: boolean | undefined;
        push: boolean;
        triage?: boolean | undefined;
        pull: boolean;
    } | undefined;
    allow_rebase_merge?: boolean | undefined;
    template_repository?: {
        id: number;
        node_id: string;
        name: string;
        full_name: string;
        license: {
            key: string;
            name: string;
            url: string | null;
            spdx_id: string | null;
            node_id: string;
            html_url?: string | undefined;
        } | null;
        forks: number;
        permissions?: {
            admin: boolean;
            pull: boolean;
            triage?: boolean | undefined;
            push: boolean;
            maintain?: boolean | undefined;
        } | undefined;
        owner: {
            name?: string | null | undefined;
            email?: string | null | undefined;
            login: string;
            id: number;
            node_id: string;
            avatar_url: string;
            gravatar_id: string | null;
            url: string;
            html_url: string;
            followers_url: string;
            following_url: string;
            gists_url: string;
            starred_url: string;
            subscriptions_url: string;
            organizations_url: string;
            repos_url: string;
            events_url: string;
            received_events_url: string;
            type: string;
            site_admin: boolean;
            starred_at?: string | undefined;
            user_view_type?: string | undefined;
        };
        private: boolean;
        html_url: string;
        description: string | null;
        fork: boolean;
        url: string;
        archive_url: string;
        assignees_url: string;
        blobs_url: string;
        branches_url: string;
        collaborators_url: string;
        comments_url: string;
        commits_url: string;
        compare_url: string;
        contents_url: string;
        contributors_url: string;
        deployments_url: string;
        downloads_url: string;
        events_url: string;
        forks_url: string;
        git_commits_url: string;
        git_refs_url: string;
        git_tags_url: string;
        git_url: string;
        issue_comment_url: string;
        issue_events_url: string;
        issues_url: string;
        keys_url: string;
        labels_url: string;
        languages_url: string;
        merges_url: string;
        milestones_url: string;
        notifications_url: string;
        pulls_url: string;
        releases_url: string;
        ssh_url: string;
        stargazers_url: string;
        statuses_url: string;
        subscribers_url: string;
        subscription_url: string;
        tags_url: string;
        teams_url: string;
        trees_url: string;
        clone_url: string;
        mirror_url: string | null;
        hooks_url: string;
        svn_url: string;
        homepage: string | null;
        language: string | null;
        forks_count: number;
        stargazers_count: number;
        watchers_count: number;
        size: number;
        default_branch: string;
        open_issues_count: number;
        is_template?: boolean | undefined;
        topics?: string[] | undefined;
        has_issues: boolean;
        has_projects: boolean;
        has_wiki: boolean;
        has_pages: boolean;
        has_downloads: boolean;
        has_discussions?: boolean | undefined;
        archived: boolean;
        disabled: boolean;
        visibility?: string | undefined;
        pushed_at: string | null;
        created_at: string | null;
        updated_at: string | null;
        allow_rebase_merge?: boolean | undefined;
        temp_clone_token?: string | undefined;
        allow_squash_merge?: boolean | undefined;
        allow_auto_merge?: boolean | undefined;
        delete_branch_on_merge?: boolean | undefined;
        allow_update_branch?: boolean | undefined;
        use_squash_pr_title_as_default?: boolean | undefined;
        squash_merge_commit_title?: "PR_TITLE" | "COMMIT_OR_PR_TITLE" | undefined;
        squash_merge_commit_message?: "PR_BODY" | "COMMIT_MESSAGES" | "BLANK" | undefined;
        merge_commit_title?: "PR_TITLE" | "MERGE_MESSAGE" | undefined;
        merge_commit_message?: "PR_TITLE" | "PR_BODY" | "BLANK" | undefined;
        allow_merge_commit?: boolean | undefined;
        allow_forking?: boolean | undefined;
        web_commit_signoff_required?: boolean | undefined;
        open_issues: number;
        watchers: number;
        master_branch?: string | undefined;
        starred_at?: string | undefined;
        anonymous_access_enabled?: boolean | undefined;
    } | null | undefined;
    temp_clone_token?: string | null | undefined;
    allow_squash_merge?: boolean | undefined;
    allow_auto_merge?: boolean | undefined;
    delete_branch_on_merge?: boolean | undefined;
    allow_merge_commit?: boolean | undefined;
    allow_update_branch?: boolean | undefined;
    use_squash_pr_title_as_default?: boolean | undefined;
    squash_merge_commit_title?: "PR_TITLE" | "COMMIT_OR_PR_TITLE" | undefined;
    squash_merge_commit_message?: "PR_BODY" | "COMMIT_MESSAGES" | "BLANK" | undefined;
    merge_commit_title?: "PR_TITLE" | "MERGE_MESSAGE" | undefined;
    merge_commit_message?: "PR_TITLE" | "PR_BODY" | "BLANK" | undefined;
    allow_forking?: boolean | undefined;
    web_commit_signoff_required?: boolean | undefined;
    subscribers_count: number;
    network_count: number;
    license: {
        key: string;
        name: string;
        url: string | null;
        spdx_id: string | null;
        node_id: string;
        html_url?: string | undefined;
    } | null;
    organization?: {
        name?: string | null | undefined;
        email?: string | null | undefined;
        login: string;
        id: number;
        node_id: string;
        avatar_url: string;
        gravatar_id: string | null;
        url: string;
        html_url: string;
        followers_url: string;
        following_url: string;
        gists_url: string;
        starred_url: string;
        subscriptions_url: string;
        organizations_url: string;
        repos_url: string;
        events_url: string;
        received_events_url: string;
        type: string;
        site_admin: boolean;
        starred_at?: string | undefined;
        user_view_type?: string | undefined;
    } | null | undefined;
    parent?: {
        id: number;
        node_id: string;
        name: string;
        full_name: string;
        license: {
            key: string;
            name: string;
            url: string | null;
            spdx_id: string | null;
            node_id: string;
            html_url?: string | undefined;
        } | null;
        forks: number;
        permissions?: {
            admin: boolean;
            pull: boolean;
            triage?: boolean | undefined;
            push: boolean;
            maintain?: boolean | undefined;
        } | undefined;
        owner: {
            name?: string | null | undefined;
            email?: string | null | undefined;
            login: string;
            id: number;
            node_id: string;
            avatar_url: string;
            gravatar_id: string | null;
            url: string;
            html_url: string;
            followers_url: string;
            following_url: string;
            gists_url: string;
            starred_url: string;
            subscriptions_url: string;
            organizations_url: string;
            repos_url: string;
            events_url: string;
            received_events_url: string;
            type: string;
            site_admin: boolean;
            starred_at?: string | undefined;
            user_view_type?: string | undefined;
        };
        private: boolean;
        html_url: string;
        description: string | null;
        fork: boolean;
        url: string;
        archive_url: string;
        assignees_url: string;
        blobs_url: string;
        branches_url: string;
        collaborators_url: string;
        comments_url: string;
        commits_url: string;
        compare_url: string;
        contents_url: string;
        contributors_url: string;
        deployments_url: string;
        downloads_url: string;
        events_url: string;
        forks_url: string;
        git_commits_url: string;
        git_refs_url: string;
        git_tags_url: string;
        git_url: string;
        issue_comment_url: string;
        issue_events_url: string;
        issues_url: string;
        keys_url: string;
        labels_url: string;
        languages_url: string;
        merges_url: string;
        milestones_url: string;
        notifications_url: string;
        pulls_url: string;
        releases_url: string;
        ssh_url: string;
        stargazers_url: string;
        statuses_url: string;
        subscribers_url: string;
        subscription_url: string;
        tags_url: string;
        teams_url: string;
        trees_url: string;
        clone_url: string;
        mirror_url: string | null;
        hooks_url: string;
        svn_url: string;
        homepage: string | null;
        language: string | null;
        forks_count: number;
        stargazers_count: number;
        watchers_count: number;
        size: number;
        default_branch: string;
        open_issues_count: number;
        is_template?: boolean | undefined;
        topics?: string[] | undefined;
        has_issues: boolean;
        has_projects: boolean;
        has_wiki: boolean;
        has_pages: boolean;
        has_downloads: boolean;
        has_discussions?: boolean | undefined;
        archived: boolean;
        disabled: boolean;
        visibility?: string | undefined;
        pushed_at: string | null;
        created_at: string | null;
        updated_at: string | null;
        allow_rebase_merge?: boolean | undefined;
        temp_clone_token?: string | undefined;
        allow_squash_merge?: boolean | undefined;
        allow_auto_merge?: boolean | undefined;
        delete_branch_on_merge?: boolean | undefined;
        allow_update_branch?: boolean | undefined;
        use_squash_pr_title_as_default?: boolean | undefined;
        squash_merge_commit_title?: "PR_TITLE" | "COMMIT_OR_PR_TITLE" | undefined;
        squash_merge_commit_message?: "PR_BODY" | "COMMIT_MESSAGES" | "BLANK" | undefined;
        merge_commit_title?: "PR_TITLE" | "MERGE_MESSAGE" | undefined;
        merge_commit_message?: "PR_TITLE" | "PR_BODY" | "BLANK" | undefined;
        allow_merge_commit?: boolean | undefined;
        allow_forking?: boolean | undefined;
        web_commit_signoff_required?: boolean | undefined;
        open_issues: number;
        watchers: number;
        master_branch?: string | undefined;
        starred_at?: string | undefined;
        anonymous_access_enabled?: boolean | undefined;
    } | undefined;
    source?: {
        id: number;
        node_id: string;
        name: string;
        full_name: string;
        license: {
            key: string;
            name: string;
            url: string | null;
            spdx_id: string | null;
            node_id: string;
            html_url?: string | undefined;
        } | null;
        forks: number;
        permissions?: {
            admin: boolean;
            pull: boolean;
            triage?: boolean | undefined;
            push: boolean;
            maintain?: boolean | undefined;
        } | undefined;
        owner: {
            name?: string | null | undefined;
            email?: string | null | undefined;
            login: string;
            id: number;
            node_id: string;
            avatar_url: string;
            gravatar_id: string | null;
            url: string;
            html_url: string;
            followers_url: string;
            following_url: string;
            gists_url: string;
            starred_url: string;
            subscriptions_url: string;
            organizations_url: string;
            repos_url: string;
            events_url: string;
            received_events_url: string;
            type: string;
            site_admin: boolean;
            starred_at?: string | undefined;
            user_view_type?: string | undefined;
        };
        private: boolean;
        html_url: string;
        description: string | null;
        fork: boolean;
        url: string;
        archive_url: string;
        assignees_url: string;
        blobs_url: string;
        branches_url: string;
        collaborators_url: string;
        comments_url: string;
        commits_url: string;
        compare_url: string;
        contents_url: string;
        contributors_url: string;
        deployments_url: string;
        downloads_url: string;
        events_url: string;
        forks_url: string;
        git_commits_url: string;
        git_refs_url: string;
        git_tags_url: string;
        git_url: string;
        issue_comment_url: string;
        issue_events_url: string;
        issues_url: string;
        keys_url: string;
        labels_url: string;
        languages_url: string;
        merges_url: string;
        milestones_url: string;
        notifications_url: string;
        pulls_url: string;
        releases_url: string;
        ssh_url: string;
        stargazers_url: string;
        statuses_url: string;
        subscribers_url: string;
        subscription_url: string;
        tags_url: string;
        teams_url: string;
        trees_url: string;
        clone_url: string;
        mirror_url: string | null;
        hooks_url: string;
        svn_url: string;
        homepage: string | null;
        language: string | null;
        forks_count: number;
        stargazers_count: number;
        watchers_count: number;
        size: number;
        default_branch: string;
        open_issues_count: number;
        is_template?: boolean | undefined;
        topics?: string[] | undefined;
        has_issues: boolean;
        has_projects: boolean;
        has_wiki: boolean;
        has_pages: boolean;
        has_downloads: boolean;
        has_discussions?: boolean | undefined;
        archived: boolean;
        disabled: boolean;
        visibility?: string | undefined;
        pushed_at: string | null;
        created_at: string | null;
        updated_at: string | null;
        allow_rebase_merge?: boolean | undefined;
        temp_clone_token?: string | undefined;
        allow_squash_merge?: boolean | undefined;
        allow_auto_merge?: boolean | undefined;
        delete_branch_on_merge?: boolean | undefined;
        allow_update_branch?: boolean | undefined;
        use_squash_pr_title_as_default?: boolean | undefined;
        squash_merge_commit_title?: "PR_TITLE" | "COMMIT_OR_PR_TITLE" | undefined;
        squash_merge_commit_message?: "PR_BODY" | "COMMIT_MESSAGES" | "BLANK" | undefined;
        merge_commit_title?: "PR_TITLE" | "MERGE_MESSAGE" | undefined;
        merge_commit_message?: "PR_TITLE" | "PR_BODY" | "BLANK" | undefined;
        allow_merge_commit?: boolean | undefined;
        allow_forking?: boolean | undefined;
        web_commit_signoff_required?: boolean | undefined;
        open_issues: number;
        watchers: number;
        master_branch?: string | undefined;
        starred_at?: string | undefined;
        anonymous_access_enabled?: boolean | undefined;
    } | undefined;
    forks: number;
    master_branch?: string | undefined;
    open_issues: number;
    watchers: number;
    anonymous_access_enabled?: boolean | undefined;
    code_of_conduct?: {
        url: string;
        key: string;
        name: string;
        html_url: string | null;
    } | undefined;
    security_and_analysis?: {
        advanced_security?: {
            status?: "enabled" | "disabled" | undefined;
        } | undefined;
        dependabot_security_updates?: {
            status?: "enabled" | "disabled" | undefined;
        } | undefined;
        secret_scanning?: {
            status?: "enabled" | "disabled" | undefined;
        } | undefined;
        secret_scanning_push_protection?: {
            status?: "enabled" | "disabled" | undefined;
        } | undefined;
        secret_scanning_non_provider_patterns?: {
            status?: "enabled" | "disabled" | undefined;
        } | undefined;
        secret_scanning_ai_detection?: {
            status?: "enabled" | "disabled" | undefined;
        } | undefined;
    } | null | undefined;
    custom_properties?: {
        [key: string]: unknown;
    } | undefined;
}, 201>>;
/**
 * 저장소 삭제
 */
declare const deleteRemoteRepo: (octokit: Octokit, options: RepoOptions, account: GithubAccount) => Promise<import("@octokit/types").OctokitResponse<never, 204>>;
/**
 * Git 설정 변경
 */
declare const setLocalConfig: (options: RepoOptions, account: GithubAccount, localPath: string) => void;
/**
 * 로컬 저장소 초기화
 */
declare const initLocalRepo: (options: RepoOptions, account: GithubAccount, localPath: string) => Promise<void>;
/**
 * 저장소 복제
 */
declare const cloneRepo: (options: RepoOptions, account: GithubAccount, localPath: string) => void;
/**
 * 저장소 초기화 (생성, 복제, 설정)
 */
declare const initRepo: (octokit: Octokit, options: RepoOptions, account: GithubAccount, localPath: string) => void;
/**
 * 저장소 복제 및 설정
 */
declare const copyRepo: (options: RepoOptions, account: GithubAccount, localPath: string) => void;
/**
 * 저장소에 변경사항 푸시
 */
declare const pushRepo: (options: RepoOptions, account: GithubAccount, localPath: string) => void;
/**
 * 새 저장소 생성 및 초기 커밋
 */
declare const makeRepo: (octokit: Octokit, options: RepoOptions, account: GithubAccount, localPath: string) => void;
/**
 * 로컬 + 원격 저장소 삭제
 */
declare const removeRepo: (octokit: Octokit, options: RepoOptions, account: GithubAccount, localPath: string) => void;
/**
 * 저장소에서 최신 변경사항을 가져오기 (pull)
 */
declare const pullRepo: (options: RepoOptions, account: GithubAccount, localPath: string) => void;
/**
 * 로컬과 원격 저장소 동기화 (sync)
 * - 로컬 변경사항이 있으면 커밋 후 푸시
 * - 원격 변경사항이 있으면 풀
 */
declare const syncRepo: (options: RepoOptions, account: GithubAccount, localPath: string) => void;
/**
 * 저장소 이슈 목록 조회
 */
declare const listRepoIssues: (octokit: Octokit, options: IssueListOptions) => Promise<{
    id: number;
    node_id: string;
    url: string;
    repository_url: string;
    labels_url: string;
    comments_url: string;
    events_url: string;
    html_url: string;
    number: number;
    state: string;
    state_reason?: "completed" | "reopened" | "not_planned" | null | undefined;
    title: string;
    body?: string | null | undefined;
    user: {
        name?: string | null | undefined;
        email?: string | null | undefined;
        login: string;
        id: number;
        node_id: string;
        avatar_url: string;
        gravatar_id: string | null;
        url: string;
        html_url: string;
        followers_url: string;
        following_url: string;
        gists_url: string;
        starred_url: string;
        subscriptions_url: string;
        organizations_url: string;
        repos_url: string;
        events_url: string;
        received_events_url: string;
        type: string;
        site_admin: boolean;
        starred_at?: string | undefined;
        user_view_type?: string | undefined;
    } | null;
    labels: (string | {
        id?: number | undefined;
        node_id?: string | undefined;
        url?: string | undefined;
        name?: string | undefined;
        description?: string | null | undefined;
        color?: string | null | undefined;
        default?: boolean | undefined;
    })[];
    assignee: {
        name?: string | null | undefined;
        email?: string | null | undefined;
        login: string;
        id: number;
        node_id: string;
        avatar_url: string;
        gravatar_id: string | null;
        url: string;
        html_url: string;
        followers_url: string;
        following_url: string;
        gists_url: string;
        starred_url: string;
        subscriptions_url: string;
        organizations_url: string;
        repos_url: string;
        events_url: string;
        received_events_url: string;
        type: string;
        site_admin: boolean;
        starred_at?: string | undefined;
        user_view_type?: string | undefined;
    } | null;
    assignees?: {
        name?: string | null | undefined;
        email?: string | null | undefined;
        login: string;
        id: number;
        node_id: string;
        avatar_url: string;
        gravatar_id: string | null;
        url: string;
        html_url: string;
        followers_url: string;
        following_url: string;
        gists_url: string;
        starred_url: string;
        subscriptions_url: string;
        organizations_url: string;
        repos_url: string;
        events_url: string;
        received_events_url: string;
        type: string;
        site_admin: boolean;
        starred_at?: string | undefined;
        user_view_type?: string | undefined;
    }[] | null | undefined;
    milestone: {
        url: string;
        html_url: string;
        labels_url: string;
        id: number;
        node_id: string;
        number: number;
        state: "open" | "closed";
        title: string;
        description: string | null;
        creator: {
            name?: string | null | undefined;
            email?: string | null | undefined;
            login: string;
            id: number;
            node_id: string;
            avatar_url: string;
            gravatar_id: string | null;
            url: string;
            html_url: string;
            followers_url: string;
            following_url: string;
            gists_url: string;
            starred_url: string;
            subscriptions_url: string;
            organizations_url: string;
            repos_url: string;
            events_url: string;
            received_events_url: string;
            type: string;
            site_admin: boolean;
            starred_at?: string | undefined;
            user_view_type?: string | undefined;
        } | null;
        open_issues: number;
        closed_issues: number;
        created_at: string;
        updated_at: string;
        closed_at: string | null;
        due_on: string | null;
    } | null;
    locked: boolean;
    active_lock_reason?: string | null | undefined;
    comments: number;
    pull_request?: {
        merged_at?: string | null | undefined;
        diff_url: string | null;
        html_url: string | null;
        patch_url: string | null;
        url: string | null;
    } | undefined;
    closed_at: string | null;
    created_at: string;
    updated_at: string;
    draft?: boolean | undefined;
    closed_by?: {
        name?: string | null | undefined;
        email?: string | null | undefined;
        login: string;
        id: number;
        node_id: string;
        avatar_url: string;
        gravatar_id: string | null;
        url: string;
        html_url: string;
        followers_url: string;
        following_url: string;
        gists_url: string;
        starred_url: string;
        subscriptions_url: string;
        organizations_url: string;
        repos_url: string;
        events_url: string;
        received_events_url: string;
        type: string;
        site_admin: boolean;
        starred_at?: string | undefined;
        user_view_type?: string | undefined;
    } | null | undefined;
    body_html?: string | undefined;
    body_text?: string | undefined;
    timeline_url?: string | undefined;
    type?: {
        id: number;
        node_id: string;
        name: string;
        description: string | null;
        color?: "gray" | "blue" | "green" | "yellow" | "orange" | "red" | "pink" | "purple" | null | undefined;
        created_at?: string | undefined;
        updated_at?: string | undefined;
        is_enabled?: boolean | undefined;
    } | null | undefined;
    repository?: {
        id: number;
        node_id: string;
        name: string;
        full_name: string;
        license: {
            key: string;
            name: string;
            url: string | null;
            spdx_id: string | null;
            node_id: string;
            html_url?: string | undefined;
        } | null;
        forks: number;
        permissions?: {
            admin: boolean;
            pull: boolean;
            triage?: boolean | undefined;
            push: boolean;
            maintain?: boolean | undefined;
        } | undefined;
        owner: {
            name?: string | null | undefined;
            email?: string | null | undefined;
            login: string;
            id: number;
            node_id: string;
            avatar_url: string;
            gravatar_id: string | null;
            url: string;
            html_url: string;
            followers_url: string;
            following_url: string;
            gists_url: string;
            starred_url: string;
            subscriptions_url: string;
            organizations_url: string;
            repos_url: string;
            events_url: string;
            received_events_url: string;
            type: string;
            site_admin: boolean;
            starred_at?: string | undefined;
            user_view_type?: string | undefined;
        };
        private: boolean;
        html_url: string;
        description: string | null;
        fork: boolean;
        url: string;
        archive_url: string;
        assignees_url: string;
        blobs_url: string;
        branches_url: string;
        collaborators_url: string;
        comments_url: string;
        commits_url: string;
        compare_url: string;
        contents_url: string;
        contributors_url: string;
        deployments_url: string;
        downloads_url: string;
        events_url: string;
        forks_url: string;
        git_commits_url: string;
        git_refs_url: string;
        git_tags_url: string;
        git_url: string;
        issue_comment_url: string;
        issue_events_url: string;
        issues_url: string;
        keys_url: string;
        labels_url: string;
        languages_url: string;
        merges_url: string;
        milestones_url: string;
        notifications_url: string;
        pulls_url: string;
        releases_url: string;
        ssh_url: string;
        stargazers_url: string;
        statuses_url: string;
        subscribers_url: string;
        subscription_url: string;
        tags_url: string;
        teams_url: string;
        trees_url: string;
        clone_url: string;
        mirror_url: string | null;
        hooks_url: string;
        svn_url: string;
        homepage: string | null;
        language: string | null;
        forks_count: number;
        stargazers_count: number;
        watchers_count: number;
        size: number;
        default_branch: string;
        open_issues_count: number;
        is_template?: boolean | undefined;
        topics?: string[] | undefined;
        has_issues: boolean;
        has_projects: boolean;
        has_wiki: boolean;
        has_pages: boolean;
        has_downloads: boolean;
        has_discussions?: boolean | undefined;
        archived: boolean;
        disabled: boolean;
        visibility?: string | undefined;
        pushed_at: string | null;
        created_at: string | null;
        updated_at: string | null;
        allow_rebase_merge?: boolean | undefined;
        temp_clone_token?: string | undefined;
        allow_squash_merge?: boolean | undefined;
        allow_auto_merge?: boolean | undefined;
        delete_branch_on_merge?: boolean | undefined;
        allow_update_branch?: boolean | undefined;
        use_squash_pr_title_as_default?: boolean | undefined;
        squash_merge_commit_title?: "PR_TITLE" | "COMMIT_OR_PR_TITLE" | undefined;
        squash_merge_commit_message?: "PR_BODY" | "COMMIT_MESSAGES" | "BLANK" | undefined;
        merge_commit_title?: "PR_TITLE" | "MERGE_MESSAGE" | undefined;
        merge_commit_message?: "PR_TITLE" | "PR_BODY" | "BLANK" | undefined;
        allow_merge_commit?: boolean | undefined;
        allow_forking?: boolean | undefined;
        web_commit_signoff_required?: boolean | undefined;
        open_issues: number;
        watchers: number;
        master_branch?: string | undefined;
        starred_at?: string | undefined;
        anonymous_access_enabled?: boolean | undefined;
    } | undefined;
    performed_via_github_app?: {
        id: number;
        slug?: string | undefined;
        node_id: string;
        client_id?: string | undefined;
        owner: {
            name?: string | null | undefined;
            email?: string | null | undefined;
            login: string;
            id: number;
            node_id: string;
            avatar_url: string;
            gravatar_id: string | null;
            url: string;
            html_url: string;
            followers_url: string;
            following_url: string;
            gists_url: string;
            starred_url: string;
            subscriptions_url: string;
            organizations_url: string;
            repos_url: string;
            events_url: string;
            received_events_url: string;
            type: string;
            site_admin: boolean;
            starred_at?: string | undefined;
            user_view_type?: string | undefined;
        } | {
            description?: string | null | undefined;
            html_url: string;
            website_url?: string | null | undefined;
            id: number;
            node_id: string;
            name: string;
            slug: string;
            created_at: string | null;
            updated_at: string | null;
            avatar_url: string;
        };
        name: string;
        description: string | null;
        external_url: string;
        html_url: string;
        created_at: string;
        updated_at: string;
        permissions: {
            [key: string]: string | undefined;
            issues?: string | undefined;
            checks?: string | undefined;
            metadata?: string | undefined;
            contents?: string | undefined;
            deployments?: string | undefined;
        };
        events: string[];
        installations_count?: number | undefined;
        client_secret?: string | undefined;
        webhook_secret?: string | null | undefined;
        pem?: string | undefined;
    } | null | undefined;
    author_association: "COLLABORATOR" | "CONTRIBUTOR" | "FIRST_TIMER" | "FIRST_TIME_CONTRIBUTOR" | "MANNEQUIN" | "MEMBER" | "NONE" | "OWNER";
    reactions?: {
        url: string;
        total_count: number;
        "+1": number;
        "-1": number;
        laugh: number;
        confused: number;
        heart: number;
        hooray: number;
        eyes: number;
        rocket: number;
    } | undefined;
    sub_issues_summary?: {
        total: number;
        completed: number;
        percent_completed: number;
    } | undefined;
}[]>;
/**
 * 저장소 이슈 생성
 */
declare const createRepoIssue: (octokit: Octokit, options: IssueCreateOptions) => Promise<{
    id: number;
    node_id: string;
    url: string;
    repository_url: string;
    labels_url: string;
    comments_url: string;
    events_url: string;
    html_url: string;
    number: number;
    state: string;
    state_reason?: "completed" | "reopened" | "not_planned" | null | undefined;
    title: string;
    body?: string | null | undefined;
    user: {
        name?: string | null | undefined;
        email?: string | null | undefined;
        login: string;
        id: number;
        node_id: string;
        avatar_url: string;
        gravatar_id: string | null;
        url: string;
        html_url: string;
        followers_url: string;
        following_url: string;
        gists_url: string;
        starred_url: string;
        subscriptions_url: string;
        organizations_url: string;
        repos_url: string;
        events_url: string;
        received_events_url: string;
        type: string;
        site_admin: boolean;
        starred_at?: string | undefined;
        user_view_type?: string | undefined;
    } | null;
    labels: (string | {
        id?: number | undefined;
        node_id?: string | undefined;
        url?: string | undefined;
        name?: string | undefined;
        description?: string | null | undefined;
        color?: string | null | undefined;
        default?: boolean | undefined;
    })[];
    assignee: {
        name?: string | null | undefined;
        email?: string | null | undefined;
        login: string;
        id: number;
        node_id: string;
        avatar_url: string;
        gravatar_id: string | null;
        url: string;
        html_url: string;
        followers_url: string;
        following_url: string;
        gists_url: string;
        starred_url: string;
        subscriptions_url: string;
        organizations_url: string;
        repos_url: string;
        events_url: string;
        received_events_url: string;
        type: string;
        site_admin: boolean;
        starred_at?: string | undefined;
        user_view_type?: string | undefined;
    } | null;
    assignees?: {
        name?: string | null | undefined;
        email?: string | null | undefined;
        login: string;
        id: number;
        node_id: string;
        avatar_url: string;
        gravatar_id: string | null;
        url: string;
        html_url: string;
        followers_url: string;
        following_url: string;
        gists_url: string;
        starred_url: string;
        subscriptions_url: string;
        organizations_url: string;
        repos_url: string;
        events_url: string;
        received_events_url: string;
        type: string;
        site_admin: boolean;
        starred_at?: string | undefined;
        user_view_type?: string | undefined;
    }[] | null | undefined;
    milestone: {
        url: string;
        html_url: string;
        labels_url: string;
        id: number;
        node_id: string;
        number: number;
        state: "open" | "closed";
        title: string;
        description: string | null;
        creator: {
            name?: string | null | undefined;
            email?: string | null | undefined;
            login: string;
            id: number;
            node_id: string;
            avatar_url: string;
            gravatar_id: string | null;
            url: string;
            html_url: string;
            followers_url: string;
            following_url: string;
            gists_url: string;
            starred_url: string;
            subscriptions_url: string;
            organizations_url: string;
            repos_url: string;
            events_url: string;
            received_events_url: string;
            type: string;
            site_admin: boolean;
            starred_at?: string | undefined;
            user_view_type?: string | undefined;
        } | null;
        open_issues: number;
        closed_issues: number;
        created_at: string;
        updated_at: string;
        closed_at: string | null;
        due_on: string | null;
    } | null;
    locked: boolean;
    active_lock_reason?: string | null | undefined;
    comments: number;
    pull_request?: {
        merged_at?: string | null | undefined;
        diff_url: string | null;
        html_url: string | null;
        patch_url: string | null;
        url: string | null;
    } | undefined;
    closed_at: string | null;
    created_at: string;
    updated_at: string;
    draft?: boolean | undefined;
    closed_by?: {
        name?: string | null | undefined;
        email?: string | null | undefined;
        login: string;
        id: number;
        node_id: string;
        avatar_url: string;
        gravatar_id: string | null;
        url: string;
        html_url: string;
        followers_url: string;
        following_url: string;
        gists_url: string;
        starred_url: string;
        subscriptions_url: string;
        organizations_url: string;
        repos_url: string;
        events_url: string;
        received_events_url: string;
        type: string;
        site_admin: boolean;
        starred_at?: string | undefined;
        user_view_type?: string | undefined;
    } | null | undefined;
    body_html?: string | undefined;
    body_text?: string | undefined;
    timeline_url?: string | undefined;
    type?: {
        id: number;
        node_id: string;
        name: string;
        description: string | null;
        color?: "gray" | "blue" | "green" | "yellow" | "orange" | "red" | "pink" | "purple" | null | undefined;
        created_at?: string | undefined;
        updated_at?: string | undefined;
        is_enabled?: boolean | undefined;
    } | null | undefined;
    repository?: {
        id: number;
        node_id: string;
        name: string;
        full_name: string;
        license: {
            key: string;
            name: string;
            url: string | null;
            spdx_id: string | null;
            node_id: string;
            html_url?: string | undefined;
        } | null;
        forks: number;
        permissions?: {
            admin: boolean;
            pull: boolean;
            triage?: boolean | undefined;
            push: boolean;
            maintain?: boolean | undefined;
        } | undefined;
        owner: {
            name?: string | null | undefined;
            email?: string | null | undefined;
            login: string;
            id: number;
            node_id: string;
            avatar_url: string;
            gravatar_id: string | null;
            url: string;
            html_url: string;
            followers_url: string;
            following_url: string;
            gists_url: string;
            starred_url: string;
            subscriptions_url: string;
            organizations_url: string;
            repos_url: string;
            events_url: string;
            received_events_url: string;
            type: string;
            site_admin: boolean;
            starred_at?: string | undefined;
            user_view_type?: string | undefined;
        };
        private: boolean;
        html_url: string;
        description: string | null;
        fork: boolean;
        url: string;
        archive_url: string;
        assignees_url: string;
        blobs_url: string;
        branches_url: string;
        collaborators_url: string;
        comments_url: string;
        commits_url: string;
        compare_url: string;
        contents_url: string;
        contributors_url: string;
        deployments_url: string;
        downloads_url: string;
        events_url: string;
        forks_url: string;
        git_commits_url: string;
        git_refs_url: string;
        git_tags_url: string;
        git_url: string;
        issue_comment_url: string;
        issue_events_url: string;
        issues_url: string;
        keys_url: string;
        labels_url: string;
        languages_url: string;
        merges_url: string;
        milestones_url: string;
        notifications_url: string;
        pulls_url: string;
        releases_url: string;
        ssh_url: string;
        stargazers_url: string;
        statuses_url: string;
        subscribers_url: string;
        subscription_url: string;
        tags_url: string;
        teams_url: string;
        trees_url: string;
        clone_url: string;
        mirror_url: string | null;
        hooks_url: string;
        svn_url: string;
        homepage: string | null;
        language: string | null;
        forks_count: number;
        stargazers_count: number;
        watchers_count: number;
        size: number;
        default_branch: string;
        open_issues_count: number;
        is_template?: boolean | undefined;
        topics?: string[] | undefined;
        has_issues: boolean;
        has_projects: boolean;
        has_wiki: boolean;
        has_pages: boolean;
        has_downloads: boolean;
        has_discussions?: boolean | undefined;
        archived: boolean;
        disabled: boolean;
        visibility?: string | undefined;
        pushed_at: string | null;
        created_at: string | null;
        updated_at: string | null;
        allow_rebase_merge?: boolean | undefined;
        temp_clone_token?: string | undefined;
        allow_squash_merge?: boolean | undefined;
        allow_auto_merge?: boolean | undefined;
        delete_branch_on_merge?: boolean | undefined;
        allow_update_branch?: boolean | undefined;
        use_squash_pr_title_as_default?: boolean | undefined;
        squash_merge_commit_title?: "PR_TITLE" | "COMMIT_OR_PR_TITLE" | undefined;
        squash_merge_commit_message?: "PR_BODY" | "COMMIT_MESSAGES" | "BLANK" | undefined;
        merge_commit_title?: "PR_TITLE" | "MERGE_MESSAGE" | undefined;
        merge_commit_message?: "PR_TITLE" | "PR_BODY" | "BLANK" | undefined;
        allow_merge_commit?: boolean | undefined;
        allow_forking?: boolean | undefined;
        web_commit_signoff_required?: boolean | undefined;
        open_issues: number;
        watchers: number;
        master_branch?: string | undefined;
        starred_at?: string | undefined;
        anonymous_access_enabled?: boolean | undefined;
    } | undefined;
    performed_via_github_app?: {
        id: number;
        slug?: string | undefined;
        node_id: string;
        client_id?: string | undefined;
        owner: {
            name?: string | null | undefined;
            email?: string | null | undefined;
            login: string;
            id: number;
            node_id: string;
            avatar_url: string;
            gravatar_id: string | null;
            url: string;
            html_url: string;
            followers_url: string;
            following_url: string;
            gists_url: string;
            starred_url: string;
            subscriptions_url: string;
            organizations_url: string;
            repos_url: string;
            events_url: string;
            received_events_url: string;
            type: string;
            site_admin: boolean;
            starred_at?: string | undefined;
            user_view_type?: string | undefined;
        } | {
            description?: string | null | undefined;
            html_url: string;
            website_url?: string | null | undefined;
            id: number;
            node_id: string;
            name: string;
            slug: string;
            created_at: string | null;
            updated_at: string | null;
            avatar_url: string;
        };
        name: string;
        description: string | null;
        external_url: string;
        html_url: string;
        created_at: string;
        updated_at: string;
        permissions: {
            [key: string]: string | undefined;
            issues?: string | undefined;
            checks?: string | undefined;
            metadata?: string | undefined;
            contents?: string | undefined;
            deployments?: string | undefined;
        };
        events: string[];
        installations_count?: number | undefined;
        client_secret?: string | undefined;
        webhook_secret?: string | null | undefined;
        pem?: string | undefined;
    } | null | undefined;
    author_association: "COLLABORATOR" | "CONTRIBUTOR" | "FIRST_TIMER" | "FIRST_TIME_CONTRIBUTOR" | "MANNEQUIN" | "MEMBER" | "NONE" | "OWNER";
    reactions?: {
        url: string;
        total_count: number;
        "+1": number;
        "-1": number;
        laugh: number;
        confused: number;
        heart: number;
        hooray: number;
        eyes: number;
        rocket: number;
    } | undefined;
    sub_issues_summary?: {
        total: number;
        completed: number;
        percent_completed: number;
    } | undefined;
}>;
/**
 * 저장소 이슈 업데이트 (상태/내용)
 */
declare const updateRepoIssue: (octokit: Octokit, options: IssueUpdateOptions) => Promise<{
    id: number;
    node_id: string;
    url: string;
    repository_url: string;
    labels_url: string;
    comments_url: string;
    events_url: string;
    html_url: string;
    number: number;
    state: string;
    state_reason?: "completed" | "reopened" | "not_planned" | null | undefined;
    title: string;
    body?: string | null | undefined;
    user: {
        name?: string | null | undefined;
        email?: string | null | undefined;
        login: string;
        id: number;
        node_id: string;
        avatar_url: string;
        gravatar_id: string | null;
        url: string;
        html_url: string;
        followers_url: string;
        following_url: string;
        gists_url: string;
        starred_url: string;
        subscriptions_url: string;
        organizations_url: string;
        repos_url: string;
        events_url: string;
        received_events_url: string;
        type: string;
        site_admin: boolean;
        starred_at?: string | undefined;
        user_view_type?: string | undefined;
    } | null;
    labels: (string | {
        id?: number | undefined;
        node_id?: string | undefined;
        url?: string | undefined;
        name?: string | undefined;
        description?: string | null | undefined;
        color?: string | null | undefined;
        default?: boolean | undefined;
    })[];
    assignee: {
        name?: string | null | undefined;
        email?: string | null | undefined;
        login: string;
        id: number;
        node_id: string;
        avatar_url: string;
        gravatar_id: string | null;
        url: string;
        html_url: string;
        followers_url: string;
        following_url: string;
        gists_url: string;
        starred_url: string;
        subscriptions_url: string;
        organizations_url: string;
        repos_url: string;
        events_url: string;
        received_events_url: string;
        type: string;
        site_admin: boolean;
        starred_at?: string | undefined;
        user_view_type?: string | undefined;
    } | null;
    assignees?: {
        name?: string | null | undefined;
        email?: string | null | undefined;
        login: string;
        id: number;
        node_id: string;
        avatar_url: string;
        gravatar_id: string | null;
        url: string;
        html_url: string;
        followers_url: string;
        following_url: string;
        gists_url: string;
        starred_url: string;
        subscriptions_url: string;
        organizations_url: string;
        repos_url: string;
        events_url: string;
        received_events_url: string;
        type: string;
        site_admin: boolean;
        starred_at?: string | undefined;
        user_view_type?: string | undefined;
    }[] | null | undefined;
    milestone: {
        url: string;
        html_url: string;
        labels_url: string;
        id: number;
        node_id: string;
        number: number;
        state: "open" | "closed";
        title: string;
        description: string | null;
        creator: {
            name?: string | null | undefined;
            email?: string | null | undefined;
            login: string;
            id: number;
            node_id: string;
            avatar_url: string;
            gravatar_id: string | null;
            url: string;
            html_url: string;
            followers_url: string;
            following_url: string;
            gists_url: string;
            starred_url: string;
            subscriptions_url: string;
            organizations_url: string;
            repos_url: string;
            events_url: string;
            received_events_url: string;
            type: string;
            site_admin: boolean;
            starred_at?: string | undefined;
            user_view_type?: string | undefined;
        } | null;
        open_issues: number;
        closed_issues: number;
        created_at: string;
        updated_at: string;
        closed_at: string | null;
        due_on: string | null;
    } | null;
    locked: boolean;
    active_lock_reason?: string | null | undefined;
    comments: number;
    pull_request?: {
        merged_at?: string | null | undefined;
        diff_url: string | null;
        html_url: string | null;
        patch_url: string | null;
        url: string | null;
    } | undefined;
    closed_at: string | null;
    created_at: string;
    updated_at: string;
    draft?: boolean | undefined;
    closed_by?: {
        name?: string | null | undefined;
        email?: string | null | undefined;
        login: string;
        id: number;
        node_id: string;
        avatar_url: string;
        gravatar_id: string | null;
        url: string;
        html_url: string;
        followers_url: string;
        following_url: string;
        gists_url: string;
        starred_url: string;
        subscriptions_url: string;
        organizations_url: string;
        repos_url: string;
        events_url: string;
        received_events_url: string;
        type: string;
        site_admin: boolean;
        starred_at?: string | undefined;
        user_view_type?: string | undefined;
    } | null | undefined;
    body_html?: string | undefined;
    body_text?: string | undefined;
    timeline_url?: string | undefined;
    type?: {
        id: number;
        node_id: string;
        name: string;
        description: string | null;
        color?: "gray" | "blue" | "green" | "yellow" | "orange" | "red" | "pink" | "purple" | null | undefined;
        created_at?: string | undefined;
        updated_at?: string | undefined;
        is_enabled?: boolean | undefined;
    } | null | undefined;
    repository?: {
        id: number;
        node_id: string;
        name: string;
        full_name: string;
        license: {
            key: string;
            name: string;
            url: string | null;
            spdx_id: string | null;
            node_id: string;
            html_url?: string | undefined;
        } | null;
        forks: number;
        permissions?: {
            admin: boolean;
            pull: boolean;
            triage?: boolean | undefined;
            push: boolean;
            maintain?: boolean | undefined;
        } | undefined;
        owner: {
            name?: string | null | undefined;
            email?: string | null | undefined;
            login: string;
            id: number;
            node_id: string;
            avatar_url: string;
            gravatar_id: string | null;
            url: string;
            html_url: string;
            followers_url: string;
            following_url: string;
            gists_url: string;
            starred_url: string;
            subscriptions_url: string;
            organizations_url: string;
            repos_url: string;
            events_url: string;
            received_events_url: string;
            type: string;
            site_admin: boolean;
            starred_at?: string | undefined;
            user_view_type?: string | undefined;
        };
        private: boolean;
        html_url: string;
        description: string | null;
        fork: boolean;
        url: string;
        archive_url: string;
        assignees_url: string;
        blobs_url: string;
        branches_url: string;
        collaborators_url: string;
        comments_url: string;
        commits_url: string;
        compare_url: string;
        contents_url: string;
        contributors_url: string;
        deployments_url: string;
        downloads_url: string;
        events_url: string;
        forks_url: string;
        git_commits_url: string;
        git_refs_url: string;
        git_tags_url: string;
        git_url: string;
        issue_comment_url: string;
        issue_events_url: string;
        issues_url: string;
        keys_url: string;
        labels_url: string;
        languages_url: string;
        merges_url: string;
        milestones_url: string;
        notifications_url: string;
        pulls_url: string;
        releases_url: string;
        ssh_url: string;
        stargazers_url: string;
        statuses_url: string;
        subscribers_url: string;
        subscription_url: string;
        tags_url: string;
        teams_url: string;
        trees_url: string;
        clone_url: string;
        mirror_url: string | null;
        hooks_url: string;
        svn_url: string;
        homepage: string | null;
        language: string | null;
        forks_count: number;
        stargazers_count: number;
        watchers_count: number;
        size: number;
        default_branch: string;
        open_issues_count: number;
        is_template?: boolean | undefined;
        topics?: string[] | undefined;
        has_issues: boolean;
        has_projects: boolean;
        has_wiki: boolean;
        has_pages: boolean;
        has_downloads: boolean;
        has_discussions?: boolean | undefined;
        archived: boolean;
        disabled: boolean;
        visibility?: string | undefined;
        pushed_at: string | null;
        created_at: string | null;
        updated_at: string | null;
        allow_rebase_merge?: boolean | undefined;
        temp_clone_token?: string | undefined;
        allow_squash_merge?: boolean | undefined;
        allow_auto_merge?: boolean | undefined;
        delete_branch_on_merge?: boolean | undefined;
        allow_update_branch?: boolean | undefined;
        use_squash_pr_title_as_default?: boolean | undefined;
        squash_merge_commit_title?: "PR_TITLE" | "COMMIT_OR_PR_TITLE" | undefined;
        squash_merge_commit_message?: "PR_BODY" | "COMMIT_MESSAGES" | "BLANK" | undefined;
        merge_commit_title?: "PR_TITLE" | "MERGE_MESSAGE" | undefined;
        merge_commit_message?: "PR_TITLE" | "PR_BODY" | "BLANK" | undefined;
        allow_merge_commit?: boolean | undefined;
        allow_forking?: boolean | undefined;
        web_commit_signoff_required?: boolean | undefined;
        open_issues: number;
        watchers: number;
        master_branch?: string | undefined;
        starred_at?: string | undefined;
        anonymous_access_enabled?: boolean | undefined;
    } | undefined;
    performed_via_github_app?: {
        id: number;
        slug?: string | undefined;
        node_id: string;
        client_id?: string | undefined;
        owner: {
            name?: string | null | undefined;
            email?: string | null | undefined;
            login: string;
            id: number;
            node_id: string;
            avatar_url: string;
            gravatar_id: string | null;
            url: string;
            html_url: string;
            followers_url: string;
            following_url: string;
            gists_url: string;
            starred_url: string;
            subscriptions_url: string;
            organizations_url: string;
            repos_url: string;
            events_url: string;
            received_events_url: string;
            type: string;
            site_admin: boolean;
            starred_at?: string | undefined;
            user_view_type?: string | undefined;
        } | {
            description?: string | null | undefined;
            html_url: string;
            website_url?: string | null | undefined;
            id: number;
            node_id: string;
            name: string;
            slug: string;
            created_at: string | null;
            updated_at: string | null;
            avatar_url: string;
        };
        name: string;
        description: string | null;
        external_url: string;
        html_url: string;
        created_at: string;
        updated_at: string;
        permissions: {
            [key: string]: string | undefined;
            issues?: string | undefined;
            checks?: string | undefined;
            metadata?: string | undefined;
            contents?: string | undefined;
            deployments?: string | undefined;
        };
        events: string[];
        installations_count?: number | undefined;
        client_secret?: string | undefined;
        webhook_secret?: string | null | undefined;
        pem?: string | undefined;
    } | null | undefined;
    author_association: "COLLABORATOR" | "CONTRIBUTOR" | "FIRST_TIMER" | "FIRST_TIME_CONTRIBUTOR" | "MANNEQUIN" | "MEMBER" | "NONE" | "OWNER";
    reactions?: {
        url: string;
        total_count: number;
        "+1": number;
        "-1": number;
        laugh: number;
        confused: number;
        heart: number;
        hooray: number;
        eyes: number;
        rocket: number;
    } | undefined;
    sub_issues_summary?: {
        total: number;
        completed: number;
        percent_completed: number;
    } | undefined;
}>;
/**
 * 저장소 프로젝트 목록 조회
 */
declare const listRepoProjects: (octokit: Octokit, options: ProjectListOptions) => Promise<{
    owner_url: string;
    url: string;
    html_url: string;
    columns_url: string;
    id: number;
    node_id: string;
    name: string;
    body: string | null;
    number: number;
    state: string;
    creator: {
        name?: string | null | undefined;
        email?: string | null | undefined;
        login: string;
        id: number;
        node_id: string;
        avatar_url: string;
        gravatar_id: string | null;
        url: string;
        html_url: string;
        followers_url: string;
        following_url: string;
        gists_url: string;
        starred_url: string;
        subscriptions_url: string;
        organizations_url: string;
        repos_url: string;
        events_url: string;
        received_events_url: string;
        type: string;
        site_admin: boolean;
        starred_at?: string | undefined;
        user_view_type?: string | undefined;
    } | null;
    created_at: string;
    updated_at: string;
    organization_permission?: "read" | "write" | "admin" | "none" | undefined;
    private?: boolean | undefined;
}[]>;
/**
 * 저장소 프로젝트 생성
 */
declare const createRepoProject: (octokit: Octokit, options: ProjectCreateOptions) => Promise<{
    owner_url: string;
    url: string;
    html_url: string;
    columns_url: string;
    id: number;
    node_id: string;
    name: string;
    body: string | null;
    number: number;
    state: string;
    creator: {
        name?: string | null | undefined;
        email?: string | null | undefined;
        login: string;
        id: number;
        node_id: string;
        avatar_url: string;
        gravatar_id: string | null;
        url: string;
        html_url: string;
        followers_url: string;
        following_url: string;
        gists_url: string;
        starred_url: string;
        subscriptions_url: string;
        organizations_url: string;
        repos_url: string;
        events_url: string;
        received_events_url: string;
        type: string;
        site_admin: boolean;
        starred_at?: string | undefined;
        user_view_type?: string | undefined;
    } | null;
    created_at: string;
    updated_at: string;
    organization_permission?: "read" | "write" | "admin" | "none" | undefined;
    private?: boolean | undefined;
}>;
/**
 * 프로젝트 컬럼 생성
 */
declare const createProjectColumn: (octokit: Octokit, options: ProjectColumnOptions) => Promise<{
    url: string;
    project_url: string;
    cards_url: string;
    id: number;
    node_id: string;
    name: string;
    created_at: string;
    updated_at: string;
}>;
/**
 * 프로젝트 카드 생성 (이슈/PR 연결 또는 노트 추가)
 */
declare const createProjectCard: (octokit: Octokit, options: ProjectCardOptions) => Promise<{
    url: string;
    id: number;
    node_id: string;
    note: string | null;
    creator: {
        name?: string | null | undefined;
        email?: string | null | undefined;
        login: string;
        id: number;
        node_id: string;
        avatar_url: string;
        gravatar_id: string | null;
        url: string;
        html_url: string;
        followers_url: string;
        following_url: string;
        gists_url: string;
        starred_url: string;
        subscriptions_url: string;
        organizations_url: string;
        repos_url: string;
        events_url: string;
        received_events_url: string;
        type: string;
        site_admin: boolean;
        starred_at?: string | undefined;
        user_view_type?: string | undefined;
    } | null;
    created_at: string;
    updated_at: string;
    archived?: boolean | undefined;
    column_name?: string | undefined;
    project_id?: string | undefined;
    column_url: string;
    content_url?: string | undefined;
    project_url: string;
}>;
/**
 * 저장소 워크플로 목록 조회
 */
declare const listRepoWorkflows: (octokit: Octokit, options: WorkflowListOptions) => Promise<{
    id: number;
    node_id: string;
    name: string;
    path: string;
    state: "active" | "deleted" | "disabled_fork" | "disabled_inactivity" | "disabled_manually";
    created_at: string;
    updated_at: string;
    url: string;
    html_url: string;
    badge_url: string;
    deleted_at?: string | undefined;
}[]>;
/**
 * 워크플로 실행 이력 조회
 */
declare const listWorkflowRuns: (octokit: Octokit, options: WorkflowRunsOptions) => Promise<{
    id: number;
    name?: string | null | undefined;
    node_id: string;
    check_suite_id?: number | undefined;
    check_suite_node_id?: string | undefined;
    head_branch: string | null;
    head_sha: string;
    path: string;
    run_number: number;
    run_attempt?: number | undefined;
    referenced_workflows?: {
        path: string;
        sha: string;
        ref?: string | undefined;
    }[] | null | undefined;
    event: string;
    status: string | null;
    conclusion: string | null;
    workflow_id: number;
    url: string;
    html_url: string;
    pull_requests: {
        id: number;
        number: number;
        url: string;
        head: {
            ref: string;
            sha: string;
            repo: {
                id: number;
                url: string;
                name: string;
            };
        };
        base: {
            ref: string;
            sha: string;
            repo: {
                id: number;
                url: string;
                name: string;
            };
        };
    }[] | null;
    created_at: string;
    updated_at: string;
    actor?: {
        name?: string | null | undefined;
        email?: string | null | undefined;
        login: string;
        id: number;
        node_id: string;
        avatar_url: string;
        gravatar_id: string | null;
        url: string;
        html_url: string;
        followers_url: string;
        following_url: string;
        gists_url: string;
        starred_url: string;
        subscriptions_url: string;
        organizations_url: string;
        repos_url: string;
        events_url: string;
        received_events_url: string;
        type: string;
        site_admin: boolean;
        starred_at?: string | undefined;
        user_view_type?: string | undefined;
    } | undefined;
    triggering_actor?: {
        name?: string | null | undefined;
        email?: string | null | undefined;
        login: string;
        id: number;
        node_id: string;
        avatar_url: string;
        gravatar_id: string | null;
        url: string;
        html_url: string;
        followers_url: string;
        following_url: string;
        gists_url: string;
        starred_url: string;
        subscriptions_url: string;
        organizations_url: string;
        repos_url: string;
        events_url: string;
        received_events_url: string;
        type: string;
        site_admin: boolean;
        starred_at?: string | undefined;
        user_view_type?: string | undefined;
    } | undefined;
    run_started_at?: string | undefined;
    jobs_url: string;
    logs_url: string;
    check_suite_url: string;
    artifacts_url: string;
    cancel_url: string;
    rerun_url: string;
    previous_attempt_url?: string | null | undefined;
    workflow_url: string;
    head_commit: {
        id: string;
        tree_id: string;
        message: string;
        timestamp: string;
        author: {
            name: string;
            email: string;
        } | null;
        committer: {
            name: string;
            email: string;
        } | null;
    } | null;
    repository: {
        id: number;
        node_id: string;
        name: string;
        full_name: string;
        owner: {
            name?: string | null | undefined;
            email?: string | null | undefined;
            login: string;
            id: number;
            node_id: string;
            avatar_url: string;
            gravatar_id: string | null;
            url: string;
            html_url: string;
            followers_url: string;
            following_url: string;
            gists_url: string;
            starred_url: string;
            subscriptions_url: string;
            organizations_url: string;
            repos_url: string;
            events_url: string;
            received_events_url: string;
            type: string;
            site_admin: boolean;
            starred_at?: string | undefined;
            user_view_type?: string | undefined;
        };
        private: boolean;
        html_url: string;
        description: string | null;
        fork: boolean;
        url: string;
        archive_url: string;
        assignees_url: string;
        blobs_url: string;
        branches_url: string;
        collaborators_url: string;
        comments_url: string;
        commits_url: string;
        compare_url: string;
        contents_url: string;
        contributors_url: string;
        deployments_url: string;
        downloads_url: string;
        events_url: string;
        forks_url: string;
        git_commits_url: string;
        git_refs_url: string;
        git_tags_url: string;
        git_url?: string | undefined;
        issue_comment_url: string;
        issue_events_url: string;
        issues_url: string;
        keys_url: string;
        labels_url: string;
        languages_url: string;
        merges_url: string;
        milestones_url: string;
        notifications_url: string;
        pulls_url: string;
        releases_url: string;
        ssh_url?: string | undefined;
        stargazers_url: string;
        statuses_url: string;
        subscribers_url: string;
        subscription_url: string;
        tags_url: string;
        teams_url: string;
        trees_url: string;
        clone_url?: string | undefined;
        mirror_url?: string | null | undefined;
        hooks_url: string;
        svn_url?: string | undefined;
        homepage?: string | null | undefined;
        language?: string | null | undefined;
        forks_count?: number | undefined;
        stargazers_count?: number | undefined;
        watchers_count?: number | undefined;
        size?: number | undefined;
        default_branch?: string | undefined;
        open_issues_count?: number | undefined;
        is_template?: boolean | undefined;
        topics?: string[] | undefined;
        has_issues?: boolean | undefined;
        has_projects?: boolean | undefined;
        has_wiki?: boolean | undefined;
        has_pages?: boolean | undefined;
        has_downloads?: boolean | undefined;
        has_discussions?: boolean | undefined;
        archived?: boolean | undefined;
        disabled?: boolean | undefined;
        visibility?: string | undefined;
        pushed_at?: string | null | undefined;
        created_at?: string | null | undefined;
        updated_at?: string | null | undefined;
        permissions?: {
            admin?: boolean | undefined;
            maintain?: boolean | undefined;
            push?: boolean | undefined;
            triage?: boolean | undefined;
            pull?: boolean | undefined;
        } | undefined;
        role_name?: string | undefined;
        temp_clone_token?: string | undefined;
        delete_branch_on_merge?: boolean | undefined;
        subscribers_count?: number | undefined;
        network_count?: number | undefined;
        code_of_conduct?: {
            key: string;
            name: string;
            url: string;
            body?: string | undefined;
            html_url: string | null;
        } | undefined;
        license?: {
            key?: string | undefined;
            name?: string | undefined;
            spdx_id?: string | undefined;
            url?: string | undefined;
            node_id?: string | undefined;
        } | null | undefined;
        forks?: number | undefined;
        open_issues?: number | undefined;
        watchers?: number | undefined;
        allow_forking?: boolean | undefined;
        web_commit_signoff_required?: boolean | undefined;
        security_and_analysis?: {
            advanced_security?: {
                status?: "enabled" | "disabled" | undefined;
            } | undefined;
            dependabot_security_updates?: {
                status?: "enabled" | "disabled" | undefined;
            } | undefined;
            secret_scanning?: {
                status?: "enabled" | "disabled" | undefined;
            } | undefined;
            secret_scanning_push_protection?: {
                status?: "enabled" | "disabled" | undefined;
            } | undefined;
            secret_scanning_non_provider_patterns?: {
                status?: "enabled" | "disabled" | undefined;
            } | undefined;
            secret_scanning_ai_detection?: {
                status?: "enabled" | "disabled" | undefined;
            } | undefined;
        } | null | undefined;
    };
    head_repository: {
        id: number;
        node_id: string;
        name: string;
        full_name: string;
        owner: {
            name?: string | null | undefined;
            email?: string | null | undefined;
            login: string;
            id: number;
            node_id: string;
            avatar_url: string;
            gravatar_id: string | null;
            url: string;
            html_url: string;
            followers_url: string;
            following_url: string;
            gists_url: string;
            starred_url: string;
            subscriptions_url: string;
            organizations_url: string;
            repos_url: string;
            events_url: string;
            received_events_url: string;
            type: string;
            site_admin: boolean;
            starred_at?: string | undefined;
            user_view_type?: string | undefined;
        };
        private: boolean;
        html_url: string;
        description: string | null;
        fork: boolean;
        url: string;
        archive_url: string;
        assignees_url: string;
        blobs_url: string;
        branches_url: string;
        collaborators_url: string;
        comments_url: string;
        commits_url: string;
        compare_url: string;
        contents_url: string;
        contributors_url: string;
        deployments_url: string;
        downloads_url: string;
        events_url: string;
        forks_url: string;
        git_commits_url: string;
        git_refs_url: string;
        git_tags_url: string;
        git_url?: string | undefined;
        issue_comment_url: string;
        issue_events_url: string;
        issues_url: string;
        keys_url: string;
        labels_url: string;
        languages_url: string;
        merges_url: string;
        milestones_url: string;
        notifications_url: string;
        pulls_url: string;
        releases_url: string;
        ssh_url?: string | undefined;
        stargazers_url: string;
        statuses_url: string;
        subscribers_url: string;
        subscription_url: string;
        tags_url: string;
        teams_url: string;
        trees_url: string;
        clone_url?: string | undefined;
        mirror_url?: string | null | undefined;
        hooks_url: string;
        svn_url?: string | undefined;
        homepage?: string | null | undefined;
        language?: string | null | undefined;
        forks_count?: number | undefined;
        stargazers_count?: number | undefined;
        watchers_count?: number | undefined;
        size?: number | undefined;
        default_branch?: string | undefined;
        open_issues_count?: number | undefined;
        is_template?: boolean | undefined;
        topics?: string[] | undefined;
        has_issues?: boolean | undefined;
        has_projects?: boolean | undefined;
        has_wiki?: boolean | undefined;
        has_pages?: boolean | undefined;
        has_downloads?: boolean | undefined;
        has_discussions?: boolean | undefined;
        archived?: boolean | undefined;
        disabled?: boolean | undefined;
        visibility?: string | undefined;
        pushed_at?: string | null | undefined;
        created_at?: string | null | undefined;
        updated_at?: string | null | undefined;
        permissions?: {
            admin?: boolean | undefined;
            maintain?: boolean | undefined;
            push?: boolean | undefined;
            triage?: boolean | undefined;
            pull?: boolean | undefined;
        } | undefined;
        role_name?: string | undefined;
        temp_clone_token?: string | undefined;
        delete_branch_on_merge?: boolean | undefined;
        subscribers_count?: number | undefined;
        network_count?: number | undefined;
        code_of_conduct?: {
            key: string;
            name: string;
            url: string;
            body?: string | undefined;
            html_url: string | null;
        } | undefined;
        license?: {
            key?: string | undefined;
            name?: string | undefined;
            spdx_id?: string | undefined;
            url?: string | undefined;
            node_id?: string | undefined;
        } | null | undefined;
        forks?: number | undefined;
        open_issues?: number | undefined;
        watchers?: number | undefined;
        allow_forking?: boolean | undefined;
        web_commit_signoff_required?: boolean | undefined;
        security_and_analysis?: {
            advanced_security?: {
                status?: "enabled" | "disabled" | undefined;
            } | undefined;
            dependabot_security_updates?: {
                status?: "enabled" | "disabled" | undefined;
            } | undefined;
            secret_scanning?: {
                status?: "enabled" | "disabled" | undefined;
            } | undefined;
            secret_scanning_push_protection?: {
                status?: "enabled" | "disabled" | undefined;
            } | undefined;
            secret_scanning_non_provider_patterns?: {
                status?: "enabled" | "disabled" | undefined;
            } | undefined;
            secret_scanning_ai_detection?: {
                status?: "enabled" | "disabled" | undefined;
            } | undefined;
        } | null | undefined;
    };
    head_repository_id?: number | undefined;
    display_title: string;
}[]>;
/**
 * 워크플로 수동 실행 (dispatch)
 */
declare const dispatchWorkflow: (octokit: Octokit, options: WorkflowDispatchOptions) => Promise<void>;
/**
 * Github 사용자 목록 조회
 * @param src - 데이터 소스 ('github' | 'local')
 * @returns Github 사용자 목록
 */
declare const findAllUsers: (src?: string) => Promise<Record<string, GithubAccount> | undefined>;
export { findGithubAccount, findAllUsers, findAllRepos, createRemoteRepo, deleteRemoteRepo, cloneRepo, setLocalConfig, initLocalRepo, initRepo, copyRepo, pushRepo, makeRepo, removeRepo, pullRepo, syncRepo, listRepoIssues, createRepoIssue, updateRepoIssue, listRepoProjects, createRepoProject, createProjectColumn, createProjectCard, listRepoWorkflows, listWorkflowRuns, dispatchWorkflow, };
//# sourceMappingURL=git.d.ts.map